In [25]:
import pandas as pd
import matplotlib.pyplot as plt
from surprise import Dataset, Reader, accuracy
import pyximport
import numpy as np
pyximport.install(setup_args={"include_dirs": np.get_include()},
                  reload_support=True)
from algorithms.knn_neighborhood import UserKNN

In [15]:
ml100k_df = pd.read_csv("data/ml-100k/ml-100k/u.data", sep="\t", header=None, names=["user_id", "item_id", "rating", "timestamp"])
ml100k_df.drop(columns=["timestamp"], inplace=True)
ml100k_df.head()

   user_id  item_id  rating
0      196      242       3
1      186      302       3
2       22      377       1
3      244       51       2
4      166      346       1

In [16]:
ml1m_df = pd.read_csv("data/ml-1m/ratings.dat", sep="::", header=None, names=["user_id", "item_id", "rating", "timestamp"])
ml1m_df.drop(columns=["timestamp"], inplace=True)
ml1m_df.head()

C:\Users\pmuellner\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.

   user_id  item_id  rating
0        1     1193       5
1        1      661       3
2        1      914       3
3        1     3408       4
4        1     2355       5

In [17]:
anime_df = pd.read_csv("data/anime_small_sample.csv", sep=";", header=None, names=["user_id", "item_id", "rating"])
anime_df.head()

   user_id  item_id  rating
0        1     8074      10
1        1    11617      10
2        1    11757      10
3        1    15451      10
4        2    11771      10

In [32]:
def run_knn(dataset_df):
    errors = []
    K = np.arange(1, 30, 1)

    reader = Reader(rating_scale=(1, 5))
    dataset = Dataset.load_from_df(dataset_df, reader=reader)
    folds = KFold(n_splits=5)
    f = 1
    for trainset, testset in folds.split(dataset):
        sim = UserKNN.compute_similarities(trainset, min_support=1)
        errors_at_fold = []
        for k in K:
            model = UserKNN(k=k, precomputed_sim=sim)
            model.fit(trainset)
            predictions = model.test(testset)
            mae = accuracy.mae(predictions, verbose=False)
            errors_at_fold.append(mae)

            print("Fold %d, k: %d, MAE: %f" % (f, k, mae))
        errors.append(errors_at_fold)
        f += 1
    return np.mean(errors, axis=0)

In [33]:
ml100k_errors = run_knn(ml100k_df)
ml1m_errors = run_knn(ml1m_df)
anime_errors = run_knn(anime_df)

Fold 1, k: 1, MAE: 1.043559
Fold 1, k: 2, MAE: 0.948891
Fold 1, k: 3, MAE: 0.901925
Fold 1, k: 4, MAE: 0.878987
Fold 1, k: 5, MAE: 0.864165
Fold 1, k: 6, MAE: 0.853963
Fold 1, k: 7, MAE: 0.844505
Fold 1, k: 8, MAE: 0.839440
Fold 1, k: 9, MAE: 0.835521
Fold 1, k: 10, MAE: 0.832539
Fold 1, k: 11, MAE: 0.829783
Fold 1, k: 12, MAE: 0.827412
Fold 1, k: 13, MAE: 0.824935
Fold 1, k: 14, MAE: 0.824176
Fold 1, k: 15, MAE: 0.822113
Fold 1, k: 16, MAE: 0.819897
Fold 1, k: 17, MAE: 0.818629
Fold 1, k: 18, MAE: 0.818003
Fold 1, k: 19, MAE: 0.817202
Fold 1, k: 20, MAE: 0.816116
Fold 1, k: 21, MAE: 0.815523
Fold 1, k: 22, MAE: 0.815347
Fold 1, k: 23, MAE: 0.814993
Fold 1, k: 24, MAE: 0.814717
Fold 1, k: 25, MAE: 0.814077
Fold 1, k: 26, MAE: 0.813034
Fold 1, k: 27, MAE: 0.812957
Fold 1, k: 28, MAE: 0.812662
Fold 1, k: 29, MAE: 0.812581
Fold 2, k: 1, MAE: 1.038523
Fold 2, k: 2, MAE: 0.933903
Fold 2, k: 3, MAE: 0.894382
Fold 2, k: 4, MAE: 0.870359
Fold 2, k: 5, MAE: 0.854976
Fold 2, k: 6, MAE: 0.845562
Fold 2, k: 7, MAE: 0.837187
Fold 2, k: 8, MAE: 0.830111
Fold 2, k: 9, MAE: 0.826154
Fold 2, k: 10, MAE: 0.822047
Fold 2, k: 11, MAE: 0.820486
Fold 2, k: 12, MAE: 0.818311
Fold 2, k: 13, MAE: 0.816837
Fold 2, k: 14, MAE: 0.815197
Fold 2, k: 15, MAE: 0.813848
Fold 2, k: 16, MAE: 0.812994
Fold 2, k: 17, MAE: 0.812084
Fold 2, k: 18, MAE: 0.811711
Fold 2, k: 19, MAE: 0.810709
Fold 2, k: 20, MAE: 0.809634
Fold 2, k: 21, MAE: 0.808691
Fold 2, k: 22, MAE: 0.808202
Fold 2, k: 23, MAE: 0.807543
Fold 2, k: 24, MAE: 0.807246
Fold 2, k: 25, MAE: 0.807014
Fold 2, k: 26, MAE: 0.806720
Fold 2, k: 27, MAE: 0.806225
Fold 2, k: 28, MAE: 0.805828
Fold 2, k: 29, MAE: 0.805389
Fold 3, k: 1, MAE: 1.040222
Fold 3, k: 2, MAE: 0.931707
Fold 3, k: 3, MAE: 0.888641
Fold 3, k: 4, MAE: 0.864842
Fold 3, k: 5, MAE: 0.851438
Fold 3, k: 6, MAE: 0.840546
Fold 3, k: 7, MAE: 0.833350
Fold 3, k: 8, MAE: 0.827989
Fold 3, k: 9, MAE: 0.823538
Fold 3, k: 10, MAE: 0.819447
Fold 3, k: 11, MAE: 0.816667
Fold 3, k: 12, MAE: 0.814104
Fold 3, k: 13, MAE: 0.813311
Fold 3, k: 14, MAE: 0.811443
Fold 3, k: 15, MAE: 0.809972
Fold 3, k: 16, MAE: 0.809042
Fold 3, k: 17, MAE: 0.808711
Fold 3, k: 18, MAE: 0.807205
Fold 3, k: 19, MAE: 0.806352
Fold 3, k: 20, MAE: 0.805617
Fold 3, k: 21, MAE: 0.804820
Fold 3, k: 22, MAE: 0.803910
Fold 3, k: 23, MAE: 0.803857
Fold 3, k: 24, MAE: 0.803725
Fold 3, k: 25, MAE: 0.803556
Fold 3, k: 26, MAE: 0.803580
Fold 3, k: 27, MAE: 0.803486
Fold 3, k: 28, MAE: 0.803334
Fold 3, k: 29, MAE: 0.802969
Fold 4, k: 1, MAE: 1.034059
Fold 4, k: 2, MAE: 0.932964
Fold 4, k: 3, MAE: 0.890693
Fold 4, k: 4, MAE: 0.866736
Fold 4, k: 5, MAE: 0.850736
Fold 4, k: 6, MAE: 0.838799
Fold 4, k: 7, MAE: 0.830738
Fold 4, k: 8, MAE: 0.825915
Fold 4, k: 9, MAE: 0.822435
Fold 4, k: 10, MAE: 0.817728
Fold 4, k: 11, MAE: 0.814648
Fold 4, k: 12, MAE: 0.812778
Fold 4, k: 13, MAE: 0.810502
Fold 4, k: 14, MAE: 0.807829
Fold 4, k: 15, MAE: 0.806994
Fold 4, k: 16, MAE: 0.805703
Fold 4, k: 17, MAE: 0.805201
Fold 4, k: 18, MAE: 0.804223
Fold 4, k: 19, MAE: 0.803779
Fold 4, k: 20, MAE: 0.803324
Fold 4, k: 21, MAE: 0.802895
Fold 4, k: 22, MAE: 0.801719
Fold 4, k: 23, MAE: 0.801054
Fold 4, k: 24, MAE: 0.800831
Fold 4, k: 25, MAE: 0.800575
Fold 4, k: 26, MAE: 0.800696
Fold 4, k: 27, MAE: 0.800174
Fold 4, k: 28, MAE: 0.799963
Fold 4, k: 29, MAE: 0.799821
Fold 5, k: 1, MAE: 1.029280
Fold 5, k: 2, MAE: 0.927558
Fold 5, k: 3, MAE: 0.886334
Fold 5, k: 4, MAE: 0.863812
Fold 5, k: 5, MAE: 0.849409
Fold 5, k: 6, MAE: 0.840095
Fold 5, k: 7, MAE: 0.834023
Fold 5, k: 8, MAE: 0.828597
Fold 5, k: 9, MAE: 0.824078
Fold 5, k: 10, MAE: 0.820988
Fold 5, k: 11, MAE: 0.818569
Fold 5, k: 12, MAE: 0.816718
Fold 5, k: 13, MAE: 0.815006
Fold 5, k: 14, MAE: 0.813619
Fold 5, k: 15, MAE: 0.812428
Fold 5, k: 16, MAE: 0.811739
Fold 5, k: 17, MAE: 0.810767
Fold 5, k: 18, MAE: 0.809809
Fold 5, k: 19, MAE: 0.808855
Fold 5, k: 20, MAE: 0.808367
Fold 5, k: 21, MAE: 0.807653
Fold 5, k: 22, MAE: 0.807055
Fold 5, k: 23, MAE: 0.806431
Fold 5, k: 24, MAE: 0.805626
Fold 5, k: 25, MAE: 0.805078
Fold 5, k: 26, MAE: 0.804753
Fold 5, k: 27, MAE: 0.804669
Fold 5, k: 28, MAE: 0.804305
Fold 5, k: 29, MAE: 0.804451
Fold 1, k: 1, MAE: 1.041170
Fold 1, k: 2, MAE: 0.928464
Fold 1, k: 3, MAE: 0.880007
Fold 1, k: 4, MAE: 0.852584
Fold 1, k: 5, MAE: 0.835695
Fold 1, k: 6, MAE: 0.823916
Fold 1, k: 7, MAE: 0.815555
Fold 1, k: 8, MAE: 0.809246
Fold 1, k: 9, MAE: 0.804211
Fold 1, k: 10, MAE: 0.800145
Fold 1, k: 11, MAE: 0.796578
Fold 1, k: 12, MAE: 0.793766
Fold 1, k: 13, MAE: 0.791197
Fold 1, k: 14, MAE: 0.788855
Fold 1, k: 15, MAE: 0.786939
Fold 1, k: 16, MAE: 0.785304
Fold 1, k: 17, MAE: 0.783784
Fold 1, k: 18, MAE: 0.782470
Fold 1, k: 19, MAE: 0.781448
Fold 1, k: 20, MAE: 0.780336
Fold 1, k: 21, MAE: 0.779402
Fold 1, k: 22, MAE: 0.778578
Fold 1, k: 23, MAE: 0.777771
Fold 1, k: 24, MAE: 0.777184
Fold 1, k: 25, MAE: 0.776545
Fold 1, k: 26, MAE: 0.775960
Fold 1, k: 27, MAE: 0.775346
Fold 1, k: 28, MAE: 0.774875
Fold 1, k: 29, MAE: 0.774353
Fold 2, k: 1, MAE: 1.039220
Fold 2, k: 2, MAE: 0.926270
Fold 2, k: 3, MAE: 0.879521
Fold 2, k: 4, MAE: 0.853604
Fold 2, k: 5, MAE: 0.836862
Fold 2, k: 6, MAE: 0.825108
Fold 2, k: 7, MAE: 0.816895
Fold 2, k: 8, MAE: 0.810168
Fold 2, k: 9, MAE: 0.805135
Fold 2, k: 10, MAE: 0.800876
Fold 2, k: 11, MAE: 0.797612
Fold 2, k: 12, MAE: 0.794957
Fold 2, k: 13, MAE: 0.792694
Fold 2, k: 14, MAE: 0.790360
Fold 2, k: 15, MAE: 0.788359
Fold 2, k: 16, MAE: 0.786669
Fold 2, k: 17, MAE: 0.785252
Fold 2, k: 18, MAE: 0.783923
Fold 2, k: 19, MAE: 0.782692
Fold 2, k: 20, MAE: 0.781572
Fold 2, k: 21, MAE: 0.780629
Fold 2, k: 22, MAE: 0.779810
Fold 2, k: 23, MAE: 0.779052
Fold 2, k: 24, MAE: 0.778324
Fold 2, k: 25, MAE: 0.777602
Fold 2, k: 26, MAE: 0.776934
Fold 2, k: 27, MAE: 0.776295
Fold 2, k: 28, MAE: 0.775744
Fold 2, k: 29, MAE: 0.775154
Fold 3, k: 1, MAE: 1.044087
Fold 3, k: 2, MAE: 0.931751
Fold 3, k: 3, MAE: 0.883969
Fold 3, k: 4, MAE: 0.857617
Fold 3, k: 5, MAE: 0.840183
Fold 3, k: 6, MAE: 0.828830
Fold 3, k: 7, MAE: 0.819876
Fold 3, k: 8, MAE: 0.813682
Fold 3, k: 9, MAE: 0.808427
Fold 3, k: 10, MAE: 0.804178
Fold 3, k: 11, MAE: 0.800507
Fold 3, k: 12, MAE: 0.797301
Fold 3, k: 13, MAE: 0.794961
Fold 3, k: 14, MAE: 0.792752
Fold 3, k: 15, MAE: 0.790809
Fold 3, k: 16, MAE: 0.789226
Fold 3, k: 17, MAE: 0.787815
Fold 3, k: 18, MAE: 0.786516
Fold 3, k: 19, MAE: 0.785331
Fold 3, k: 20, MAE: 0.784112
Fold 3, k: 21, MAE: 0.783016
Fold 3, k: 22, MAE: 0.782232
Fold 3, k: 23, MAE: 0.781436
Fold 3, k: 24, MAE: 0.780767
Fold 3, k: 25, MAE: 0.780086
Fold 3, k: 26, MAE: 0.779562
Fold 3, k: 27, MAE: 0.778908
Fold 3, k: 28, MAE: 0.778324
Fold 3, k: 29, MAE: 0.777761
Fold 4, k: 1, MAE: 1.046165
Fold 4, k: 2, MAE: 0.929358
Fold 4, k: 3, MAE: 0.881994
Fold 4, k: 4, MAE: 0.854539
Fold 4, k: 5, MAE: 0.837452
Fold 4, k: 6, MAE: 0.825267
Fold 4, k: 7, MAE: 0.817181
Fold 4, k: 8, MAE: 0.810561
Fold 4, k: 9, MAE: 0.805033
Fold 4, k: 10, MAE: 0.800458
Fold 4, k: 11, MAE: 0.796986
Fold 4, k: 12, MAE: 0.794026
Fold 4, k: 13, MAE: 0.791395
Fold 4, k: 14, MAE: 0.789394
Fold 4, k: 15, MAE: 0.787435
Fold 4, k: 16, MAE: 0.785613
Fold 4, k: 17, MAE: 0.783967
Fold 4, k: 18, MAE: 0.782521
Fold 4, k: 19, MAE: 0.781169
Fold 4, k: 20, MAE: 0.780298
Fold 4, k: 21, MAE: 0.779190
Fold 4, k: 22, MAE: 0.778300
Fold 4, k: 23, MAE: 0.777565
Fold 4, k: 24, MAE: 0.776848
Fold 4, k: 25, MAE: 0.776222
Fold 4, k: 26, MAE: 0.775582
Fold 4, k: 27, MAE: 0.775099
Fold 4, k: 28, MAE: 0.774477
Fold 4, k: 29, MAE: 0.773909
Fold 5, k: 1, MAE: 1.039534
Fold 5, k: 2, MAE: 0.924975
Fold 5, k: 3, MAE: 0.877465
Fold 5, k: 4, MAE: 0.851822
Fold 5, k: 5, MAE: 0.836005
Fold 5, k: 6, MAE: 0.824215
Fold 5, k: 7, MAE: 0.815347
Fold 5, k: 8, MAE: 0.808340
Fold 5, k: 9, MAE: 0.803351
Fold 5, k: 10, MAE: 0.798927
Fold 5, k: 11, MAE: 0.795430
Fold 5, k: 12, MAE: 0.792471
Fold 5, k: 13, MAE: 0.789880
Fold 5, k: 14, MAE: 0.787526
Fold 5, k: 15, MAE: 0.785554
Fold 5, k: 16, MAE: 0.784055
Fold 5, k: 17, MAE: 0.782614
Fold 5, k: 18, MAE: 0.781281
Fold 5, k: 19, MAE: 0.779905
Fold 5, k: 20, MAE: 0.778863
Fold 5, k: 21, MAE: 0.777815
Fold 5, k: 22, MAE: 0.776633
Fold 5, k: 23, MAE: 0.775821
Fold 5, k: 24, MAE: 0.775227
Fold 5, k: 25, MAE: 0.774470

Fold 5, k: 26, MAE: 0.773818
Fold 5, k: 27, MAE: 0.773208
Fold 5, k: 28, MAE: 0.772645
Fold 5, k: 29, MAE: 0.772065
Fold 1, k: 1, MAE: 2.949514
Fold 1, k: 2, MAE: 2.926052
Fold 1, k: 3, MAE: 2.922731
Fold 1, k: 4, MAE: 2.921920
Fold 1, k: 5, MAE: 2.921753
Fold 1, k: 6, MAE: 2.921641
Fold 1, k: 7, MAE: 2.921539
Fold 1, k: 8, MAE: 2.921493
Fold 1, k: 9, MAE: 2.921498
Fold 1, k: 10, MAE: 2.921507
Fold 1, k: 11, MAE: 2.921508
Fold 1, k: 12, MAE: 2.921523
Fold 1, k: 13, MAE: 2.921520
Fold 1, k: 14, MAE: 2.921514
Fold 1, k: 15, MAE: 2.921511
Fold 1, k: 16, MAE: 2.921504
Fold 1, k: 17, MAE: 2.921505
Fold 1, k: 18, MAE: 2.921510
Fold 1, k: 19, MAE: 2.921506
Fold 1, k: 20, MAE: 2.921511
Fold 1, k: 21, MAE: 2.921517
Fold 1, k: 22, MAE: 2.921522
Fold 1, k: 23, MAE: 2.921518
Fold 1, k: 24, MAE: 2.921514
Fold 1, k: 25, MAE: 2.921509
Fold 1, k: 26, MAE: 2.921509
Fold 1, k: 27, MAE: 2.921506
Fold 1, k: 28, MAE: 2.921499
Fold 1, k: 29, MAE: 2.921498
Fold 2, k: 1, MAE: 2.946892
Fold 2, k: 2, MAE: 2.925549
Fold 2, k: 3, MAE: 2.921764
Fold 2, k: 4, MAE: 2.921093
Fold 2, k: 5, MAE: 2.920836
Fold 2, k: 6, MAE: 2.920716
Fold 2, k: 7, MAE: 2.920667
Fold 2, k: 8, MAE: 2.920606
Fold 2, k: 9, MAE: 2.920576
Fold 2, k: 10, MAE: 2.920540
Fold 2, k: 11, MAE: 2.920551
Fold 2, k: 12, MAE: 2.920533
Fold 2, k: 13, MAE: 2.920538
Fold 2, k: 14, MAE: 2.920525
Fold 2, k: 15, MAE: 2.920525
Fold 2, k: 16, MAE: 2.920533
Fold 2, k: 17, MAE: 2.920512
Fold 2, k: 18, MAE: 2.920513
Fold 2, k: 19, MAE: 2.920509
Fold 2, k: 20, MAE: 2.920514
Fold 2, k: 21, MAE: 2.920511
Fold 2, k: 22, MAE: 2.920512
Fold 2, k: 23, MAE: 2.920517
Fold 2, k: 24, MAE: 2.920512
Fold 2, k: 25, MAE: 2.920512
Fold 2, k: 26, MAE: 2.920517
Fold 2, k: 27, MAE: 2.920519
Fold 2, k: 28, MAE: 2.920515
Fold 2, k: 29, MAE: 2.920514
Fold 3, k: 1, MAE: 2.942204
Fold 3, k: 2, MAE: 2.921510
Fold 3, k: 3, MAE: 2.917891
Fold 3, k: 4, MAE: 2.917113
Fold 3, k: 5, MAE: 2.916819
Fold 3, k: 6, MAE: 2.916630
Fold 3, k: 7, MAE: 2.916583
Fold 3, k: 8, MAE: 2.916530
Fold 3, k: 9, MAE: 2.916521
Fold 3, k: 10, MAE: 2.916499
Fold 3, k: 11, MAE: 2.916462
Fold 3, k: 12, MAE: 2.916435
Fold 3, k: 13, MAE: 2.916420
Fold 3, k: 14, MAE: 2.916404
Fold 3, k: 15, MAE: 2.916395
Fold 3, k: 16, MAE: 2.916407
Fold 3, k: 17, MAE: 2.916398
Fold 3, k: 18, MAE: 2.916395
Fold 3, k: 19, MAE: 2.916397
Fold 3, k: 20, MAE: 2.916391
Fold 3, k: 21, MAE: 2.916388
Fold 3, k: 22, MAE: 2.916377
Fold 3, k: 23, MAE: 2.916375
Fold 3, k: 24, MAE: 2.916388
Fold 3, k: 25, MAE: 2.916386
Fold 3, k: 26, MAE: 2.916382
Fold 3, k: 27, MAE: 2.916385
Fold 3, k: 28, MAE: 2.916386
Fold 3, k: 29, MAE: 2.916390
Fold 4, k: 1, MAE: 2.953778
Fold 4, k: 2, MAE: 2.932643
Fold 4, k: 3, MAE: 2.929082
Fold 4, k: 4, MAE: 2.928524
Fold 4, k: 5, MAE: 2.928285
Fold 4, k: 6, MAE: 2.928199
Fold 4, k: 7, MAE: 2.928159
Fold 4, k: 8, MAE: 2.928119
Fold 4, k: 9, MAE: 2.928091
Fold 4, k: 10, MAE: 2.928073
Fold 4, k: 11, MAE: 2.928061
Fold 4, k: 12, MAE: 2.928039
Fold 4, k: 13, MAE: 2.928010
Fold 4, k: 14, MAE: 2.928003
Fold 4, k: 15, MAE: 2.927974
Fold 4, k: 16, MAE: 2.927974
Fold 4, k: 17, MAE: 2.927979
Fold 4, k: 18, MAE: 2.927972
Fold 4, k: 19, MAE: 2.927956
Fold 4, k: 20, MAE: 2.927958
Fold 4, k: 21, MAE: 2.927965
Fold 4, k: 22, MAE: 2.927969
Fold 4, k: 23, MAE: 2.927964
Fold 4, k: 24, MAE: 2.927959
Fold 4, k: 25, MAE: 2.927954
Fold 4, k: 26, MAE: 2.927962
Fold 4, k: 27, MAE: 2.927963
Fold 4, k: 28, MAE: 2.927964
Fold 4, k: 29, MAE: 2.927967
Fold 5, k: 1, MAE: 2.943330
Fold 5, k: 2, MAE: 2.922296
Fold 5, k: 3, MAE: 2.918933
Fold 5, k: 4, MAE: 2.918156
Fold 5, k: 5, MAE: 2.917902
Fold 5, k: 6, MAE: 2.917823
Fold 5, k: 7, MAE: 2.917806
Fold 5, k: 8, MAE: 2.917796
Fold 5, k: 9, MAE: 2.917816
Fold 5, k: 10, MAE: 2.917784
Fold 5, k: 11, MAE: 2.917786
Fold 5, k: 12, MAE: 2.917776
Fold 5, k: 13, MAE: 2.917777
Fold 5, k: 14, MAE: 2.917784
Fold 5, k: 15, MAE: 2.917769
Fold 5, k: 16, MAE: 2.917764
Fold 5, k: 17, MAE: 2.917749
Fold 5, k: 18, MAE: 2.917731
Fold 5, k: 19, MAE: 2.917734
Fold 5, k: 20, MAE: 2.917732
Fold 5, k: 21, MAE: 2.917721
Fold 5, k: 22, MAE: 2.917724
Fold 5, k: 23, MAE: 2.917723
Fold 5, k: 24, MAE: 2.917718
Fold 5, k: 25, MAE: 2.917714
Fold 5, k: 26, MAE: 2.917714
Fold 5, k: 27, MAE: 2.917716
Fold 5, k: 28, MAE: 2.917712
Fold 5, k: 29, MAE: 2.917713

In [ ]:
plt.plot(K, ml100k_errors, label="ML-100k")
plt.plot(K, ml1m_errors, label="ML-1M")
plt.plot(K, anime_errors, label="Anime")
plt.legend()